# 以降のリクエストで利用するURL
@baseUrl = http://localhost:4004/taskEntity
@queryUrl = http://localhost:4004/query
@employeeUrl = http://localhost:4004/employee

# 未認証
### ------------------------------------------------------------------------
# サービスのメタデータドキュメントを取得する
GET {{baseUrl}}/TaskEntity
### ------------------------------------------------------------------------
