# 以降のリクエストで利用するURL
@baseUrl = http://localhost:4004/user

# 未認証
### ------------------------------------------------------------------------
# サービスのメタデータドキュメントを取得する
GET {{baseUrl}}/$metadata
### ------------------------------------------------------------------------
# ログインユーザー情報を取得する
GET {{baseUrl}}/profile


# 認証済み
### ------------------------------------------------------------------------
# サービスのメタデータドキュメントを取得する
GET {{baseUrl}}/$metadata
Authorization: Basic test1@example.com:abc

### ------------------------------------------------------------------------
# ログインユーザー情報を取得する
GET {{baseUrl}}/profile
Authorization: Basic test1@example.com:abc

### ------------------------------------------------------------------------
# ログインユーザー情報を取得する
GET {{baseUrl}}/profile
Authorization: Basic test1@example.com:abc

### ------------------------------------------------------------------------
# ログインユーザー情報を取得する
GET {{baseUrl}}/profile
Authorization: Basic admin@example.com:admin

### ------------------------------------------------------------------------
# ログインユーザー情報を取得する
GET {{baseUrl}}/home
Authorization: Basic admin@example.com:admin